env:
    token: "ENCRYPTED[aeafe03efdcc70074a92dc0172e3fe0c687c8a732da714f9fc0deec9459bbb1405dff70839e91762d3288b2aba290a83]"
    chat_id: "@nexus_to"

Munch_task:
  name: "Nexus-Kernel-Munch"
  container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
      cpu: 8
      memory: 32G

  Setup_script:
    - bash setup.sh

  Build_script:
    - cd kernel
    - bash build.sh null munch lto

Alioth_task:
  name: "Nexus-Kernel-Aloith"
  container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
      cpu: 8
      memory: 32G

  Setup_script:
    - bash setup.sh

  Build_script:
    - cd kernel
    - bash build.sh null alioth lto

Apollo_task:
  name: "Nexus-Kernel-Apollo"
  container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
      cpu: 8
      memory: 32G

  Setup_script:
    - bash setup.sh

  Build_script:
    - cd kernel
    - bash build.sh null apollo lto

Cmi_task:
  name: "Nexus-Kernel-Cmi"
  container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
      cpu: 8
      memory: 32G

  Setup_script:
    - bash setup.sh

  Build_script:
    - cd kernel
    - bash build.sh null cmi lto

Lmi_task:
  name: "Nexus-Kernel-Lmi"
  container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
      cpu: 8
      memory: 32G

  Setup_script:
    - bash setup.sh

  Build_script:
    - cd kernel
    - bash build.sh null lmi lto

Umi_task:
  name: "Nexus-Kernel-Umi"
  container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
      cpu: 8
      memory: 32G

  Setup_script:
    - bash setup.sh

  Build_script:
    - cd kernel
    - bash build.sh null umi lto
